version: '3'
services:
  nginx:
    image: nginx:1.17.6-alpine
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./app/[projectname]/public:/var/www/html/public
      - ./etc/nginx/default.template.conf:/etc/nginx/default.template
    ports:
      - 80:80
      - 9000:9000
    environment:
      - NGINX_HOST=nginx_host
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
  php:
      build:
        context: ./
      restart: always
      # volumes:
      #   - ./app/[projectname]:/var/www/html

  mysql:
    image: mysql:8.0.18
    container_name: mysql_host
    restart: always
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/app.cnf
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./app/[projectname]/misc/docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root # = MYSQL_ROOT_PASSWORD
    ports:
      - 8080:80